#!/usr/bin/env node
// Pull the crew roster from the Google Sheet and write src/data/roster.ts.
// The sheet is the source of truth; nothing here is invented. Run: npm run sync
//
// Sheet columns: Date (d/m/Y) | Status | Heads
// Only rows with a real date AND a named head become bookings. Empty "Heads"
// rows are treated as unbooked, which is what they are.

import { writeFile } from "node:fs/promises";

const SHEET_ID = "1xNwpHgYQzx6mAGPm-tsQjrXw6zfCb0gMWerFirw5dc0";
const CSV = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=0`;

// Minimal CSV parse: handles quoted fields containing commas.
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else quoted = false;
      } else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else if (c !== "\r") field += c;
  }
  if (field || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

function parseDate(value) {
  const m = String(value).trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/);
  if (!m) return null;
  let [, d, mo, y] = m;
  y = Number(y);
  if (y < 100) y += 2000;
  const iso = `${y}-${String(mo).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
  const dt = new Date(`${iso}T12:00:00Z`);
  return Number.isNaN(dt.getTime()) ? null : iso;
}

function mapStatus(raw) {
  const v = String(raw || "").trim().toLowerCase();
  if (v.startsWith("lock")) return "Confirmed";
  if (v === "keen") return "Pencilled";
  if (v === "vacant" || v === "") return "Open Guest";
  return "Open Guest";
}

const res = await fetch(CSV, { redirect: "follow" });
if (!res.ok) {
  console.error(`Sheet fetch failed: ${res.status}. Is it still link-shared?`);
  process.exit(1);
}
const text = await res.text();
if (/^\s*<(!doctype|html)/i.test(text)) {
  console.error("Got HTML, not CSV — the sheet is no longer publicly readable.");
  process.exit(1);
}

const rows = parseCsv(text);
const bookings = [];
for (const r of rows) {
  const date = parseDate(r[0]);
  if (!date) continue;
  const heads = String(r[2] || "").trim().replace(/\s+/g, " ");
  if (!heads) continue; // unbooked slot, not a booking
  bookings.push({ date, status: mapStatus(r[1]), dj: heads });
}
bookings.sort((a, b) => a.date.localeCompare(b.date));

const out = `// GENERATED by tools/sync-roster.mjs from the crew Google Sheet.
// Do not edit by hand — edit the sheet and run: npm run sync
// Source: https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit
// Synced rows: ${bookings.length}

export type ShowStatus = "Confirmed" | "Pencilled" | "Open Guest" | "Induction";

export type RosterItem = {
  date: string;
  time: string;
  dj: string;
  mc: string;
  guest: string;
  status: ShowStatus;
  notes: string;
};

export const SHOW_TIME = "12:00-1:30PM";

export const roster: RosterItem[] = [
${bookings
  .map(
    (b) => `  {
    date: "${b.date}",
    time: SHOW_TIME,
    dj: ${JSON.stringify(b.dj)},
    mc: "",
    guest: "",
    status: "${b.status}",
    notes: ""
  }`
  )
  .join(",\n")}
];
`;

await writeFile(new URL("../src/data/roster.ts", import.meta.url), out);
const future = bookings.filter((b) => b.date >= new Date().toISOString().slice(0, 10));
console.log(`Synced ${bookings.length} bookings from the sheet.`);
console.log(`Latest booking: ${bookings.at(-1)?.date} — ${bookings.at(-1)?.dj}`);
console.log(`Future bookings: ${future.length}`);
if (!future.length) {
  console.log("No upcoming bookings in the sheet — the site will show line-up TBA.");
}
