// GENERATED by tools/sync-roster.mjs from the crew Google Sheet.
// Do not edit by hand — edit the sheet and run: npm run sync
// Source: https://docs.google.com/spreadsheets/d/1xNwpHgYQzx6mAGPm-tsQjrXw6zfCb0gMWerFirw5dc0/edit
// Synced rows: 41
//
// Bookings only, all values literal. The types and upcomingSlots() live in
// roster.ts so a bad generation cannot remove an export the pages import.

export type RosterBooking = {
  date: string;
  time: string;
  dj: string;
  mc: string;
  guest: string;
  status: "Confirmed" | "Pencilled" | "Open Guest" | "Induction";
  notes: string;
};

export const bookings: RosterBooking[] = [
  {
    date: "2023-07-22",
    time: "12:00-1:30PM",
    dj: "Adrian & Bronx",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-08-05",
    time: "12:00-1:30PM",
    dj: "Pace Notes",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-08-19",
    time: "12:00-1:30PM",
    dj: "Pace Notes & Tea Money",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-08-26",
    time: "12:00-1:30PM",
    dj: "Tea $$ with guest Bronx",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-09-02",
    time: "12:00-1:30PM",
    dj: "Tea $$",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-09-16",
    time: "12:00-1:30PM",
    dj: "Pace Notes - Jazzy styles LQ 1x slot 🫖 💴 breaking on the bench/couch",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-09-23",
    time: "12:00-1:30PM",
    dj: "Tiff guest 30min 🫖 💵",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-09-30",
    time: "12:00-1:30PM",
    dj: "Pacenotes 90min",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-10-07",
    time: "12:00-1:30PM",
    dj: "Gee keen Lego Keen ☺️ 🫖 💵",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2023-10-14",
    time: "12:00-1:30PM",
    dj: "Btka Michael Picard Negative pace 🫖 💴",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-10-28",
    time: "12:00-1:30PM",
    dj: "Jim Westlake Trip Hazard 🔥🔥",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-11-11",
    time: "12:00-1:30PM",
    dj: "Mighty MC Manaki pacenotes 90min set",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-12-02",
    time: "12:00-1:30PM",
    dj: "coxy & pacenotes",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-12-09",
    time: "12:00-1:30PM",
    dj: "free julian & pacenotes",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2023-12-16",
    time: "12:00-1:30PM",
    dj: "Bronx & Tea money",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2023-12-23",
    time: "12:00-1:30PM",
    dj: "Merry Christmas 😘",
    mc: "",
    guest: "",
    status: "Open Guest",
    notes: ""
  },
  {
    date: "2023-12-30",
    time: "12:00-1:30PM",
    dj: "Dom Brightmore",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-01-06",
    time: "12:00-1:30PM",
    dj: "Digital & shout out show",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-01-13",
    time: "12:00-1:30PM",
    dj: "C1 hour set b2b spin fx?",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-01-20",
    time: "12:00-1:30PM",
    dj: "Btka & Pacenotes",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-02-03",
    time: "12:00-1:30PM",
    dj: "Leng lewn & Tea money",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-02-10",
    time: "12:00-1:30PM",
    dj: "Dusty wings",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-02-17",
    time: "12:00-1:30PM",
    dj: "Fuss 90min",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-03-16",
    time: "12:00-1:30PM",
    dj: "Jacko",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-03-23",
    time: "12:00-1:30PM",
    dj: "Tamen 60 min set w/ interview - PaceNotes",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-04-06",
    time: "12:00-1:30PM",
    dj: "LQ & PaceNotes",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-04-13",
    time: "12:00-1:30PM",
    dj: "Erney D - PaceNots",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-04-20",
    time: "12:00-1:30PM",
    dj: "Gemini guest mix - pacenotes",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-05-04",
    time: "12:00-1:30PM",
    dj: "Gee & Rudi sound Take over",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-05-25",
    time: "12:00-1:30PM",
    dj: "Pacenotes - LQ [TechStep B2B set]",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-06-01",
    time: "12:00-1:30PM",
    dj: "Tim Reaper Future Retro day of Trace gig",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-08-17",
    time: "12:00-1:30PM",
    dj: "MC Manaki - Conrad tribute",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-09-14",
    time: "12:00-1:30PM",
    dj: "Erney Dee",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-10-12",
    time: "12:00-1:30PM",
    dj: "Glen Clancey",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-10-19",
    time: "12:00-1:30PM",
    dj: "Defect Jayden",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2024-11-16",
    time: "12:00-1:30PM",
    dj: "douglas",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2024-12-07",
    time: "12:00-1:30PM",
    dj: "rob dog",
    mc: "",
    guest: "",
    status: "Open Guest",
    notes: ""
  },
  {
    date: "2025-01-18",
    time: "12:00-1:30PM",
    dj: "Pace Notes",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2025-02-01",
    time: "12:00-1:30PM",
    dj: "Ageusic",
    mc: "",
    guest: "",
    status: "Pencilled",
    notes: ""
  },
  {
    date: "2025-02-08",
    time: "12:00-1:30PM",
    dj: "jacko",
    mc: "",
    guest: "",
    status: "Open Guest",
    notes: ""
  },
  {
    date: "2025-02-15",
    time: "12:00-1:30PM",
    dj: "Dub divination guest",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  }
];
