// GENERATED by tools/sync-roster.mjs from the crew Google Sheet.
// Do not edit by hand — edit the sheet and run: npm run sync
// Source: https://docs.google.com/spreadsheets/d/1xNwpHgYQzx6mAGPm-tsQjrXw6zfCb0gMWerFirw5dc0/edit
// Synced rows: 8
//
// Bookings only, all values literal. The types and upcomingSlots() live in
// roster.ts so a bad generation cannot remove an export the pages import.

export type RosterBooking = {
  date: string;
  time: string;
  dj: string;
  mc: string;
  guest: string;
  status: "Confirmed" | "Pencilled" | "Open Guest" | "Induction";
  notes: string;
};

export const bookings: RosterBooking[] = [
  {
    date: "2026-05-23",
    time: "12:00-1:30PM",
    dj: "Jacko",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2026-06-13",
    time: "12:00-1:30PM",
    dj: "Glen w/ guest Ibby",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2026-07-04",
    time: "12:00-1:30PM",
    dj: "Rob",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2026-07-11",
    time: "12:00-1:30PM",
    dj: "Glen",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2026-08-01",
    time: "12:00-1:30PM",
    dj: "Rob",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2026-08-08",
    time: "12:00-1:30PM",
    dj: "Glen w guest Wasteman",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2026-09-05",
    time: "12:00-1:30PM",
    dj: "Rob",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  },
  {
    date: "2026-10-03",
    time: "12:00-1:30PM",
    dj: "Rob",
    mc: "",
    guest: "",
    status: "Confirmed",
    notes: ""
  }
];
