// GENERATED by "Publish to site" on /tools.
// Bookings only, all values literal. The types and upcomingSlots() live in
// roster.ts so publishing cannot remove an export the pages import.

export type RosterBooking = {
  date: string;
  time: string;
  dj: string;
  mc: string;
  guest: string;
  status: "Confirmed" | "Pencilled" | "Open Guest" | "Induction";
  notes: string;
};

export const bookings: RosterBooking[] = [
  {
    date: "2026-09-26",
    time: "12:00-1:30PM",
    dj: "SpinFX X Phil K X Spikey T",
    mc: "special Live Recordings",
    guest: "",
    status: "Open Guest",
    notes: "Jungle, Hardcore, DNB, UKG & Bass music from Melbourne. Live on Kiss FM Australia. Stream on the Kiss FM app or kissfm.com.au. Listen back to the archive and get show updates at counterculture.vip"
  }
];
